
package com.indiegnition.libraryrest.services.rest;

import org.json.JSONObject;


/**
 * Code autogenerated. Do not modify this file.
 */

// TODO BORRAR cuando se incluyan DTOAs

public interface DTO {
    /**
     * Hace una asignacion de los parametros dados por el JSON
     * @param jsonObject el JSON recibido
     */
    void setFromJSON(JSONObject jsonObject);

    /**
     * Convierte la estructura DTO a su correspondiente DTO
     * @return el DTO generado
     */
    
    
    JSONObject toJSON();
}


