
package com.indiegnition.libraryrest.models;
import com.indiegnition.libraryrest.services.rest.DTO;

import org.json.JSONException;
import org.json.JSONObject;

/**
 * Code autogenerated. Do not modify this file.
 */
public class UserDTO implements DTO {
	// region - Members, getters and setters

	private Integer id;
	public Integer getId () { return id; }
	public void setId (Integer id) { this.id = id; }


	private String email;
	public String getEmail () { return email; }
	public void setEmail (String email) { this.email = email; }
	
	
	// endregion
	
	
	
	// region - Constructor and JSON <->
	
	public UserDTO() {
		// Empty constructor
	}
	
	@Override
	public void setFromJSON (JSONObject json) {
		try {
			if (!JSONObject.NULL.equals(json.opt("Id"))) {
				this.id = (Integer) json.opt("Id");
			}

			if (!JSONObject.NULL.equals(json.opt("Email"))) {
				this.email = (String) json.opt("Email");
			}
		}
		catch (Exception e) {
			e.printStackTrace();
		}
	}
	
	public JSONObject toJSON () {
		JSONObject json = new JSONObject();
		
		try {
			json.put("Id", this.id);

			  if (this.email != null)
				json.put("Email", this.email);
		}
		catch (JSONException e) {
			e.printStackTrace();
		}
		
		return json;
	}


	// endregion
}

	